### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
Added Contributing guide 
#15

### CODE REVIEW

**Comment by carlzoo** [comment]
I think this is better in a separate contributing.md file.

**Comment by the-amazing-atharva** [comment]
Agreed!
Should I make a new file ?

**Comment by carlzoo** [comment]
Yes

**Comment by the-amazing-atharva** [comment]
Done!

Once you merge the PR, I will link the text to the appropriate file

**Review by carlzoo — APPROVED** [review]

**Pull request merged**
